import React, { Suspense, lazy, useState, useEffect } from 'react';
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle, Smartphone, Clock, ChevronLeft, ChevronRight, Calendar, Database, Sparkles, Presentation } from "lucide-react";
import { Link } from "react-router-dom";
import { Helmet } from 'react-helmet-async';
import { coursesData } from "@/data/categoryCourses";
import { VideoTestimonialCarousel } from "@/components/VideoTestimonialCarousel";
import { StudentReviewCarousel } from "@/components/StudentReviewCarousel";
import sriaLogo from '@/assets/sria-logo.png';

// Both are below-the-fold / interaction-only on the homepage, so they're
// code-split out of the critical bundle: CourseCarousel pulls in
// embla-carousel-react, DemoModal only matters once a user opens it.
const CourseCarousel = lazy(() => import("@/components/CourseCarousel").then(m => ({ default: m.CourseCarousel })));
const DemoModal = lazy(() => import("@/components/DemoModal").then(m => ({ default: m.DemoModal })));

const CarouselFallback = () => (
  <div className="h-[340px] rounded-xl bg-gray-100 animate-pulse" />
);

const sapCategories = [
  { title: "SAP Technical & Development", hours: "Advanced coding, configuration, and technical architecture modules.", link: "/courses/sap-technical" },
  { title: "SAP Functional Modules", hours: "Finance, Materials Management, Sales & Distribution, and more.", link: "/courses/sap-functional" },
  { title: "SAP Business Technology Platform (BTP)", hours: "Cloud integration and digital transformation modules.", link: "/courses/sap-btp" },
];
const sapCourses = [
  { ...coursesData.find(c => c.id === "sap-abap-course-training"), title: "SAP ABAP on S/4 HANA", duration: "8-10 Weeks", link: "/courses/sap-abap-course-training" },
  { ...coursesData.find(c => c.id === "sap-abap-cds-course-training"), title: "SAP ABAP & CDS", duration: "8-10 Weeks", link: "/courses/sap-abap-cds-course-training" },
  { ...coursesData.find(c => c.id === "sap-fiori-course-training"), title: "SAP FIORI UI5", duration: "40+ Hours", link: "/courses/sap-fiori-course-training" },
  { ...coursesData.find(c => c.id === "sap-basis-course-training"), title: "SAP BASIS", duration: "40+ Hours", link: "/courses/sap-basis-course-training" },
  { ...coursesData.find(c => c.id === "sap-fico-course-training"), title: "SAP FICO On S4 HANA", duration: "2-3 Months", link: "/courses/sap-fico-course-training" },
  { ...coursesData.find(c => c.id === "sap-sd-course-training"), title: "SAP SD On S4 HANA", duration: "10-12 Weeks", link: "/courses/sap-sd-course-training" },
  { ...coursesData.find(c => c.id === "sap-mm-course-training"), title: "SAP MM On S4 HANA", duration: "8-10 Weeks", link: "/courses/sap-mm-course-training" },
  { ...coursesData.find(c => c.id === "sap-pp-course-training"), title: "SAP PP On S4 HANA", duration: "8-10 Weeks", link: "/courses/sap-pp-course-training" },
  { ...coursesData.find(c => c.id === "sap-qm-course-training"), title: "SAP QM On S4 HANA", duration: "8-10 Weeks", link: "/courses/sap-qm-course-training" },
].map(c => ({
  title: c.title || "",
  duration: c.duration || "",
  link: c.link || "",
  image: c.image && c.image !== "code-icon" ? c.image : undefined
}));

const trendingCourses = [
  /* Commented out per request - Data Analytics trending course
  {
    title: "Data Analytics",
    hours: "70 Hours",
    link: "/courses/data-analytics",
    image: "/data-analytics.jpg"
  },
  */
  {
    title: "Python",
    hours: "45 Hours",
    link: "/courses/python",
    image: "/python.jpg"
  },
  /* Commented out per request - Digital Marketing trending course
  {
    title: "Digital Marketing",
    hours: "Multiple Courses",
    link: "/courses/digital-marketing",
    image: "/digital-marketing.JPG"
  },
  */
  {
    title: "AIML",
    hours: "80 Hours",
    link: "/courses/aiml",
    image: "/aiml.jpg"
  },
  {
    title: "AI",
    hours: "80 Hours",
    link: "/courses/ai",
    image: "/ai.jpg"
  },
];

// Each slide's WebP variants are pre-generated by gen-webp.cjs (480w for
// mobile, full width for desktop/retina). `sizes` mirrors the carousel
// container's CSS (~100vw on mobile, capped at 600px from lg: up).
const HERO_IMAGE_SIZES = '(max-width: 1023px) 100vw, 600px';
const HERO_IMAGES = [
  {
    src: '/hero-bg-4.png', width: 1200, height: 675,
    webpSrcSet: '/hero-bg-4-480w.webp 480w, /hero-bg-4-1200w.webp 1200w',
    link: 'https://docs.google.com/forms/d/e/1FAIpQLSdXT8Mx2S5-wBwOrevQ_09OYcvV0oYFFHznNrYg_5RQQ9OBrw/viewform?usp=publish-editor',
  },
  {
    src: '/hero-bg-3.png', width: 1200, height: 800,
    webpSrcSet: '/hero-bg-3-480w.webp 480w, /hero-bg-3-1200w.webp 1200w',
  },
  {
    src: '/hero-bg-1.jpeg', width: 1080, height: 810,
    webpSrcSet: '/hero-bg-1-480w.webp 480w, /hero-bg-1-1080w.webp 1080w',
  },
  {
    src: '/hero-bg-2.jpeg', width: 1200, height: 900,
    webpSrcSet: '/hero-bg-2-480w.webp 480w, /hero-bg-2-1200w.webp 1200w',
  },
  {
    src: '/hero-image.jpg', width: 1080, height: 810,
    webpSrcSet: '/hero-image-480w.webp 480w, /hero-image-1080w.webp 1080w',
  },
];

const Home = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isDemoModalOpen, setIsDemoModalOpen] = useState(false);
  // Only the first hero slide is rendered on initial paint (it's the LCP
  // candidate). The rest are mounted well after `load` so they never compete
  // for bandwidth with the LCP image on a slow connection - requestIdleCallback
  // alone isn't enough here since it only tracks CPU idleness, not the
  // network still being busy fetching the first slide + other page assets.
  const [otherSlidesReady, setOtherSlidesReady] = useState(false);

  useEffect(() => {
    let timer: ReturnType<typeof setTimeout>;
    const scheduleOtherSlides = () => {
      timer = setTimeout(() => setOtherSlidesReady(true), 2000);
    };
    if (document.readyState === 'complete') {
      scheduleOtherSlides();
    } else {
      window.addEventListener('load', scheduleOtherSlides, { once: true });
    }
    return () => {
      window.removeEventListener('load', scheduleOtherSlides);
      clearTimeout(timer);
    };
  }, []);

  // Auto-advance carousel every 5 seconds
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % HERO_IMAGES.length);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % HERO_IMAGES.length);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + HERO_IMAGES.length) % HERO_IMAGES.length);
  };

  const goToSlide = (index: number) => {
    setCurrentSlide(index);
  };

  const siteUrl = "https://nxgentechacademy.com";

  return (
    <div className="min-h-screen font-sans text-gray-800 overflow-x-hidden">
      <Helmet>
        <title>NxGen Tech Academy | Hyderabad</title>
        <meta name="description" content="NxGen Tech Academy is the leading IT training institute in Hyderabad, offering professional courses in SAP, Python, Data Science, and more with 100% placement assistance." />
        <link rel="canonical" href={siteUrl} />

        {/* Open Graph Tags */}
        <meta property="og:title" content="Best IT Training Institute in Hyderabad | NxGen Tech Academy" />
        <meta property="og:description" content="Join the best IT training institute in Hyderabad for SAP, Python, Data Science, and more. Get 100% placement assistance." />
        <meta property="og:url" content={siteUrl} />
        <meta property="og:type" content="website" />
        <meta property="og:image" content={`${siteUrl}/og-image.jpg`} />
      </Helmet>

      {/* Hero Section with Carousel */}
      <section className="relative bg-white text-gray-800 py-2 lg:py-4 overflow-hidden">
        <div className="w-full px-4 md:px-10 lg:px-20 mx-auto grid lg:grid-cols-2 gap-8 lg:gap-12 items-center lg:items-start">
          {/* Left Content */}
          <div className="order-2 lg:order-1 space-y-6 z-10">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-[#000080]/10 text-[#000080] rounded-full text-xs sm:text-sm font-bold uppercase tracking-wider">
              IT Training Institute in Hyderabad
            </div>

            <div>
              <h1 className="text-3xl lg:text-4xl font-bold leading-tight text-black">
                Build Job-Ready IT Skills for Your Career
              </h1>
              <p className="text-lg md:text-xl text-[#000080] font-semibold mt-4 leading-snug">
                Bridge the gap between learning and industry requirements with practical training in SAP, Python, and AI/ML.
              </p>
            </div>

            <p className="text-base sm:text-lg text-gray-600 leading-relaxed">
              Learn from experienced trainers, work on practical projects, and develop the skills you need to confidently take your next step in the IT industry.
            </p>

            <div className="grid grid-cols-2 gap-3">
              {[
                "Practical, Hands-On Training",
                "Project-Based Learning",
                "Industry-Relevant Skills",
                "Career-Focused Preparation",
              ].map((title, i) => (
                <span key={i} className="inline-flex items-center justify-center gap-2 px-3 py-2 rounded-full bg-[#000080] text-white font-bold text-xs sm:text-sm shadow-sm text-center">
                  <CheckCircle className="w-4 h-4 text-secondary shrink-0" />
                  {title}
                </span>
              ))}
            </div>

            <div className="flex flex-col sm:flex-row flex-wrap gap-4 pt-2 w-full">
              <Button asChild size="lg" className="bg-secondary hover:bg-secondary/90 text-white font-medium text-lg px-8 rounded-md w-full sm:w-auto">
                <Link to="/training-programs">Explore Courses</Link>
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="border-[#000080] text-[#000080] hover:bg-[#000080] hover:text-white font-medium text-lg px-8 rounded-md w-full sm:w-auto"
                onClick={() => setIsDemoModalOpen(true)}
              >
                Book a Free Demo
              </Button>
            </div>

            {isDemoModalOpen && (
              <Suspense fallback={null}>
                <DemoModal
                  isOpen={isDemoModalOpen}
                  onClose={() => setIsDemoModalOpen(false)}
                />
              </Suspense>
            )}

            <p className="text-sm text-gray-500 leading-relaxed max-w-xl">
              IT Training Institute in Hyderabad offering SAP, Python, and AI/ML training for students, graduates, and working professionals.
            </p>

            <div className="pt-2">
              <p className="text-base sm:text-lg font-bold text-[#000080] border-l-4 border-secondary pl-3">
                Learn. Build. Prepare. Move Forward in Your IT Career.
              </p>
              <div className="h-0.5 w-full bg-gray-200 mt-4 max-w-md"></div>
            </div>
          </div>

          {/* Right Image Carousel */}
          <div className="order-1 lg:order-2 relative flex flex-col items-center lg:items-end -mx-4 md:-mx-10 lg:mx-0 mb-6 lg:mb-0 lg:mt-0 lg:sticky lg:top-24">
            {/* Carousel Container */}
            <div className="relative w-full max-w-full lg:max-w-[600px] h-[260px] sm:h-[400px] lg:h-[600px] mx-auto lg:mx-0">
              {/* Images - only slide 0 (the LCP candidate) mounts on first
                  paint; the rest mount once the browser is idle so hidden
                  slides don't compete for bandwidth during initial render. */}
              {HERO_IMAGES.map((image, index) => {
                if (index !== 0 && !otherSlidesReady && index !== currentSlide) return null;

                const imgElement = (
                  <picture>
                    <source type="image/webp" srcSet={image.webpSrcSet} sizes={HERO_IMAGE_SIZES} />
                    <img
                      src={image.src}
                      width={image.width}
                      height={image.height}
                      alt={`Hero slide ${index + 1}`}
                      loading={index === 0 ? 'eager' : 'lazy'}
                      fetchPriority={index === 0 ? 'high' : undefined}
                      decoding={index === 0 ? 'sync' : 'async'}
                      className={`absolute inset-0 w-full h-full object-cover lg:object-contain transition-opacity duration-1000 ${index === currentSlide ? 'opacity-100 z-10' : 'opacity-0 z-0'
                        } ${image.link ? 'cursor-pointer' : ''}`}
                    />
                  </picture>
                );

                return (
                  <div key={index}>
                    {image.link ? (
                      <a href={image.link} target="_blank" rel="noopener noreferrer">
                        {imgElement}
                      </a>
                    ) : (
                      imgElement
                    )}
                  </div>
                );
              })}

              {/* Navigation Arrows */}
              <button
                onClick={prevSlide}
                className="absolute left-2 top-1/2 -translate-y-1/2 z-20 bg-white/80 hover:bg-white text-gray-800 p-2 rounded-full shadow-lg transition-[transform,background-color] duration-300 hover:scale-110"
                aria-label="Previous slide"
              >
                <ChevronLeft className="w-5 h-5" />
              </button>

              <button
                onClick={nextSlide}
                className="absolute right-2 top-1/2 -translate-y-1/2 z-20 bg-white/80 hover:bg-white text-gray-800 p-2 rounded-full shadow-lg transition-[transform,background-color] duration-300 hover:scale-110"
                aria-label="Next slide"
              >
                <ChevronRight className="w-5 h-5" />
              </button>

              {/* Carousel Indicators */}
              <div className="absolute bottom-4 left-1/2 -translate-x-1/2 z-20 flex gap-2">
                {HERO_IMAGES.map((_, index) => (
                  <button
                    key={index}
                    onClick={() => goToSlide(index)}
                    className={`h-2 w-2 rounded-full origin-left transition-[transform,background-color] duration-300 ${index === currentSlide
                      ? 'bg-[#000080] scale-x-[4]'
                      : 'bg-primary/50 scale-x-100 hover:bg-primary/50'
                      }`}
                    aria-label={`Go to slide ${index + 1}`}
                  />
                ))}
              </div>
            </div>

            {/* Founded By - highlighted trust badge */}
            <div className="mt-6 w-full max-w-full lg:max-w-[600px] mx-auto lg:mx-0">
              <div className="flex items-center gap-4 bg-gradient-to-r from-[#000080]/[0.06] to-secondary/10 border border-[#000080]/15 rounded-2xl p-4 sm:p-5 shadow-sm">
                <div className="bg-white rounded-xl p-2.5 shadow-sm shrink-0 border border-gray-100">
                  <img src={sriaLogo} alt="SRIA Infotech Logo" width={140} height={50} decoding="async" className="h-10 sm:h-12 object-contain" />
                </div>
                <div>
                  <p className="text-xs uppercase tracking-wider font-bold text-secondary">Founded by</p>
                  <p className="text-gray-900 font-bold text-base sm:text-lg leading-snug">SRIA Infotech Pvt. Ltd.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Why Choose Us */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <h2 className="text-3xl font-bold mb-4 text-primary">Why Do Professionals Choose Our Institution?</h2>
            <div className="w-20 h-1 bg-secondary mx-auto rounded-full mb-6"></div>
            <p className="text-gray-600 leading-relaxed">
              Working professionals choose NxGen Tech Academy because we focus on results, relevance, and reliability. We combine academic depth with industry exposure, which strengthens our position among the <b>top software training institutes in Hyderabad with placements.</b>
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              "Expert instructors with 10+ years of industry experience",
              "Industry-relevant certification programs",
              "Hands-on labs and real-time project exposure",
              "100% job placement assistance",
              "Flexible weekend and weekday schedules",
              "Global certification guidance"
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-4 p-6 bg-white rounded-lg shadow-sm hover:shadow-md transition-all border-l-4 border-secondary">
                <CheckCircle className="w-6 h-6 text-secondary flex-shrink-0 mt-1" />
                <p className="text-lg font-semibold">{item}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Our Associations (Government Partnership) - hidden for now */}
      {false && (
        <section className="py-20 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-[#000080] via-[#000080] to-[#00004d]" />
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-[#22c55e]/20 rounded-full blur-3xl" />
          <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-white/10 rounded-full blur-3xl" />
          <div className="absolute inset-0 opacity-[0.06] bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] pointer-events-none" />

          <div className="container mx-auto px-4 relative z-10">
            <div className="text-center max-w-2xl mx-auto mb-12">
              <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-white/10 border border-white/20 rounded-full text-white text-xs font-bold uppercase tracking-wider mb-4">
                <Sparkles className="w-3.5 h-3.5 text-[#22c55e]" /> Government Partnership
              </div>
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Our Associations</h2>
              <p className="text-white/70 text-lg">Trusted collaborations that strengthen our training ecosystem</p>
            </div>

            <Link
              to="/bsnl-skill-development-partner"
              className="group relative flex flex-col sm:flex-row items-center gap-8 max-w-3xl mx-auto bg-white rounded-[2rem] p-8 sm:p-10 shadow-2xl hover:shadow-[0_25px_60px_-15px_rgba(34,197,94,0.4)] transition-all duration-300 hover:-translate-y-1.5"
            >
              <div className="absolute -top-3 -right-3 md:top-6 md:right-6 bg-[#22c55e] text-white text-[10px] md:text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider shadow-md">
                Official Partner
              </div>

              <div className="w-28 h-28 shrink-0 rounded-2xl bg-white border border-gray-100 shadow-inner flex items-center justify-center overflow-hidden p-3 group-hover:border-[#22c55e]/40 transition-colors">
                <img
                  src="/bsnl-logo.png"
                  alt="BSNL Logo"
                  width={112}
                  height={112}
                  loading="lazy"
                  decoding="async"
                  className="w-full h-full object-contain group-hover:scale-110 transition-transform duration-500"
                />
              </div>

              <div className="text-center sm:text-left flex-1">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-green-50 text-[#000080] rounded-full font-bold text-xs uppercase tracking-wide mb-2">
                  <span className="w-1.5 h-1.5 bg-[#22c55e] rounded-full animate-pulse" /> BSNL RTTC Skill Development Partner
                </div>
                <h3 className="text-2xl font-bold text-gray-900 group-hover:text-[#000080] transition-colors mb-1">BSNL Regional Telecom Training Centre (RTTC), Hyderabad</h3>
                <p className="text-gray-500 text-sm">Practical training in AI, Cloud, Networking & Telecom technologies</p>
              </div>
              <div className="hidden sm:flex items-center gap-2 text-[#000080] font-bold shrink-0 bg-[#000080]/5 group-hover:bg-[#000080] group-hover:text-white px-5 py-3 rounded-xl transition-colors">
                View Details <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
          </div>
        </section>
      )}

      {/* SAP Academy Feature */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="flex flex-col lg:flex-row gap-12 items-center">
            <div className="lg:w-1/2">
              <img
                src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1000&auto=format&fit=crop"
                alt="Students learning"
                width={1000}
                height={400}
                loading="lazy"
                decoding="async"
                className="rounded-2xl shadow-xl w-full object-cover h-[400px]"
              />
            </div>
            <div className="lg:w-1/2 space-y-6">
              <div className="inline-block bg-primary/10 text-primary font-bold px-4 py-1 rounded-full text-sm">Featured Program</div>
              <h2 className="text-3xl lg:text-4xl font-bold text-primary">SAP Academy for Enterprise Solutions</h2>
              <p className="text-gray-600 leading-relaxed text-lg">
                Our <b>SAP Academy for Enterprise Solutions</b> prepares professionals to become SAP Certified Experts. The program combines structured coursework with enterprise-level practical implementation.
              </p>
              <ul className="space-y-3">
                <li className="flex items-center gap-2 text-gray-700">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  <span>Qualification: Graduate & Master’s Background in Commerce, Management, IT, Engineering, or related fields.</span>
                </li>
                <li className="flex items-center gap-2 text-gray-700">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  <span>Prerequisite: Basic understanding of any programming language.</span>
                </li>
              </ul>
              <Button className="bg-secondary hover:bg-secondary/90 text-white mt-4" asChild>
                <Link to="/training-programs">Explore More <ArrowRight className="ml-2 w-4 h-4" /></Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* SAP Courses Grid */}
      {/* <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold mb-10 text-center text-primary">SAP Categories</h2>
          <CourseCarousel items={sapCategories} type="category" />
        </div>
      </section> */}

      {/* Trending Courses Carousel */}
      <section className="py-10 lg:py-12">
        <div className="w-full px-4 md:px-10 lg:px-20 mx-auto">
          <h2 className="text-3xl font-bold mb-10 text-center text-primary">Trending Courses</h2>
          <Suspense fallback={<CarouselFallback />}>
            <CourseCarousel items={trendingCourses} type="course" />
          </Suspense>
        </div>
      </section>

      {/* SAP Courses Grid */}
      <section className="py-10 lg:py-12">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold mb-10 text-center text-primary">SAP Courses</h2>
          <Suspense fallback={<CarouselFallback />}>
            <CourseCarousel items={sapCourses} type="course" />
          </Suspense>
          <div className="text-center mt-10">
            <Button asChild variant="outline" className="border-primary text-primary hover:bg-primary hover:text-white">
              <Link to="/courses/sap-courses">View All SAP Courses</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-10 lg:py-12 bg-primary/5">
        <div className="w-full px-4 md:px-10 lg:px-20 mx-auto">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <h2 className="text-3xl font-bold mb-4 text-primary">Testimonials</h2>
            <div className="w-20 h-1 bg-secondary mx-auto rounded-full mb-6"></div>
            <p className="text-gray-600">Hear from our successful students who transformed their careers with NxGen Tech Academy.</p>
          </div>

          {/* Video Testimonials */}
          <div className="mb-20">
            <h3 className="text-2xl font-bold mb-8 text-primary uppercase tracking-wider">Video Success Stories</h3>
            <VideoTestimonialCarousel
              items={[
                { id: "v1", youtubeId: "AZEZc7j5jDg", title: "" },
                { id: "v2", youtubeId: "Y019HAHgJvc", title: "" },
                { id: "v3", youtubeId: "f8JehiagC40", title: "" },
                { id: "v4", youtubeId: "-pkVqNifeOA", title: "" },
                { id: "v5", youtubeId: "zWoBwPb2C6Y", title: "" },
                { id: "v6", youtubeId: "YMkN-vbyY9U", title: "" },
                { id: "v7", youtubeId: "ZtRi5g89wkU", title: "" },
                { id: "v8", youtubeId: "OFWzuvcjyWI", title: "" },
                { id: "v9", youtubeId: "saMGWM-ELnw", title: "" },
              ]}
            />
          </div>

          <div className="flex items-center justify-between gap-3 mb-8">
            <h3 className="text-2xl font-bold text-primary">Google Reviews</h3>
            <span className="inline-flex items-center bg-gray-100 text-gray-700 px-3 py-1.5 rounded-full text-sm font-bold shrink-0">
              4.9
            </span>
          </div>
          <StudentReviewCarousel
            items={[
              { name: "Archana", text: "I had a great learning experience at NxGen Tech Academy. The teaching approach is practical, and the support from the team is excellent.", rating: 5 },
              { name: "Ashwitha Aldandi", text: "I had a wonderful experience at NxGen Tech Academy. The SAP ABAP training was industry-oriented and included real-time assignments and live project exposure. The faculty was knowledgeable, approachable, and always willing to help. The overall learning environment was excellent, and I would recommend this academy to students and freshers who want practical SAP training.", rating: 5 },
              { name: "Achhe Kavya", text: "I had a great learning experience at NxGen Tech Academy. The trainers were supportive and provided excellent guidance throughout the learning journey. The hands-on training in Python, SQL, and Django helped me strengthen my technical skills and gain practical experience. It is a great place for anyone looking to build a career in software development.", rating: 5 },
            ]}
          />
        </div>
      </section>

      {/* Recent Articles */}
      {/* <section className="py-20">
        <div className="w-full px-4 md:px-10 lg:px-20 mx-auto">
          <h2 className="text-3xl font-bold mb-10 text-center text-primary">Recent Articles</h2>
          <div className="grid md:grid-cols-3 gap-8">
            {isLoadingBlogs ? (
              <div className="col-span-3 text-center py-10">
                <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-primary mx-auto"></div>
                <p className="mt-4 text-gray-500">Loading recent articles...</p>
              </div>
            ) : latestBlogs.length > 0 ? (
              latestBlogs.map((blog, i) => (
                <Link to={`/blogs/${blog.slug}`} key={blog.id || i} className="group cursor-pointer block">
                  <div className="bg-gray-200 h-48 rounded-lg mb-4 relative overflow-hidden">
                    <div className="absolute inset-0 bg-primary/20 group-hover:bg-primary/0 transition-colors"></div>
                    {blog.image_url ? (
                      <img
                        src={blog.image_url}
                        alt={blog.title}
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                        onError={(e) => { (e.target as any).src = "https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=800&auto=format&fit=crop"; }}
                      />
                    ) : (
                      <div className="w-full h-full bg-slate-100 flex items-center justify-center">
                        <Sparkles className="w-10 h-10 text-slate-300" />
                      </div>
                    )}
                  </div>
                  <p className="text-xs text-secondary font-bold mb-1">
                    {blog.created_at ? new Date(blog.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : ""}
                  </p>
                  <h3 className="font-bold text-lg leading-snug group-hover:text-primary transition-colors line-clamp-2">
                    {blog.title}
                  </h3>
                </Link>
              ))
            ) : (
              <p className="col-span-3 text-center text-gray-500 py-10">No recent articles found.</p>
            )}
          </div>
        </div>
      </section> */}

      {/* WhatsApp quick chat button now rendered globally in App.tsx */}
    </div>
  );
};

export default Home;